### ISSUE TITLE
Certify not working on dev

### ISSUE THREAD

**Issue by jakemco** [bulatb/yuno#10]
I put a bunch of filenames in a list and tried to pipe it to `yuno certify -`, but got an error.

```
$ cat foo
phase1/check2/incdec-const-errors.rc
phase1/check3b/type-conflict-assignment.rc
phase1/check4/if-while-bad.rc
phase1/check5/function-call-bad.rc
phase1/check6b/not-assignable.rc
phase1/check6b/reference-bad.rc
phase1/check7/illegal-exit-bad.rc
phase2/check10/array-declaration-bad.rc
phase2/check11a/array-usage-bad.rc
phase2/check12a/foreach-bad.rc
phase2/check12b/break-continue-bad.rc
phase2/check13a/struct-decl-bad.rc
phase2/check13b/struct-decl-recursive-bad.rc
phase2/check14b/struct-this-bad.rc
phase2/check8/const-init-bad.rc
phase2/check8/divide-by-zero.rc
phase3/check15a/pointer-deref-bad.rc
phase3/check15b/pointer-deref-lhs-bad.rc
phase3/check16/delete-new-bad.rc

$ cat foo | yuno certify -
Generating answer files for piped-in tests
Traceback (most recent call last):
  File "/Users/jakem/Code/cs/cs131/yuno/yuno.py", line 26, in <module>
    main()
  File "/Users/jakem/Code/cs/cs131/yuno/yuno.py", line 23, in main
    program.main(options.tail)
  File "/Users/jakem/Code/cs/cs131/yuno/yuno/certify/certify.py", line 85, in main
    command_handlers[options.command](options)
  File "/Users/jakem/Code/cs/cs131/yuno/yuno/certify/certify.py", line 69, in _certify_pipe
    harness.run_set(tests)
  File "/Users/jakem/Code/cs/cs131/yuno/yuno/certify/testing.py", line 137, in run_set
    test.run_in_harness(self)
  File "/Users/jakem/Code/cs/cs131/yuno/yuno/core/testing.py", line 165, in run_in_harness
    harness.test_failed(self, output, expected_output)
  File "/Users/jakem/Code/cs/cs131/yuno/yuno/core/testing.py", line 241, in test_failed
    if self.diff_routine:
AttributeError: 'AnswerGeneratingHarness' object has no attribute 'diff_routine'
```

**Comment by bulatb** [comment]
Good catch. That's actually been lurking for a while, apparently. I need some better test coverage.
